/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/contabilidade/apuramento-iva': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['contabilidade.apuramento-iva.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/apuramento-iva/{apuramentoIva}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.apuramento-iva.show']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/artigos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.artigos.index']
    put?: never
    post: operations['faturacao.artigos.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/artigos/{artigo}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.artigos.show']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/forgot-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.forgot-password']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/reset-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.reset-password']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['auth.me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/change-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['auth.change-password']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/clientes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.clientes.index']
    put?: never
    post: operations['faturacao.clientes.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/clientes/{cliente}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.clientes.show']
    put: operations['faturacao.clientes.update']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/plano-de-contas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.contas.index']
    put?: never
    post: operations['contabilidade.contas.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/plano-de-contas/{conta}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['contabilidade.contas.update']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/faturas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.faturas.index']
    put?: never
    post: operations['faturacao.faturas.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/faturas/{fatura}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.faturas.show']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/faturas/{fatura}/anular': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['faturacao.faturas.anular']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/faturas/{fatura}/pdf': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * A geração do PDF nunca é síncrona (ver ARCHITECTURE.md): se ainda
     *     não existir, despacha o Job e devolve 202 em vez de bloquear o
     *     pedido HTTP
     */
    get: operations['faturacao.faturas.pdf']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/faturas/{fatura}/qrcode': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.faturas.qrcode']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/lancamentos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.lancamentos.index']
    put?: never
    post: operations['contabilidade.lancamentos.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/lancamentos/{lancamento}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.lancamentos.show']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/lancamentos/{lancamento}/anular': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['contabilidade.lancamentos.anular']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/faturas/{fatura}/pagamentos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.pagamentos.index']
    put?: never
    post: operations['faturacao.pagamentos.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/periodos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.periodos.index']
    put?: never
    post: operations['contabilidade.periodos.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/periodos/{periodoContabil}/fechar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['contabilidade.periodos.fechar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/periodos-fiscais': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.periodos-fiscais.index']
    put?: never
    post: operations['faturacao.periodos-fiscais.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/periodos-fiscais/{periodoFiscal}/fechar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['faturacao.periodos-fiscais.fechar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/balancete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.balancete']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/balanco': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.balanco']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/contabilidade/demonstracao-resultados': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['contabilidade.demonstracao-resultados']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/saft/exportar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['faturacao.saft.exportar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/series': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.series.index']
    put?: never
    post: operations['faturacao.series.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/series/{serie}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.series.show']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/faturacao/taxas-cambio': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['faturacao.taxas-cambio.index']
    put?: never
    post: operations['faturacao.taxas-cambio.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/admin/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['admin.users.index']
    put?: never
    post: operations['admin.users.store']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/admin/users/{user}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['admin.users.show']
    put: operations['admin.users.update']
    post?: never
    delete: operations['admin.users.destroy']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/admin/users/{user}/reset-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['admin.users.reset-password']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AnularFaturaRequest */
    AnularFaturaRequest: {
      /** Format: uuid */
      serie_nc_id: string
      motivo: string
    }
    /** ApuramentoIvaResource */
    ApuramentoIvaResource: {
      id: string
      /** @constant */
      type: 'apuramento_iva'
      attributes: {
        periodo_id: string
        iva_liquidado: {
          amount: string
          currency: string
        } | null
        iva_dedutivel: {
          amount: string
          currency: string
        } | null
        iva_apurado: {
          amount: string
          currency: string
        } | null
        lancamento_id: string
        data_apuramento: string | null
      }
      created_at: string | null
      updated_at: string | null
    }
    /** ApurarIvaRequest */
    ApurarIvaRequest: {
      /** Format: uuid */
      periodo_id: string
    }
    /** ArtigoCollection */
    ArtigoCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** ArtigoResource */
    ArtigoResource: {
      id: string
      /** @constant */
      type: 'artigo'
      attributes: {
        codigo: string
        nome: string
        preco_unitario: {
          amount: string
          currency: string
        } | null
        taxa_iva: string
        unidade: string
      }
      created_at: string | null
      updated_at: string | null
    }
    /** BalancoResource */
    BalancoResource: {
      activo: components['schemas']['LinhaDemonstrativoResource'][]
      passivo: components['schemas']['LinhaDemonstrativoResource'][]
      capital_proprio: components['schemas']['LinhaDemonstrativoResource'][]
      resultado_acumulado: {
        amount: string
        currency: string
      } | null
      total_activo: {
        amount: string
        currency: string
      } | null
      total_passivo: {
        amount: string
        currency: string
      } | null
      total_capital_proprio: {
        amount: string
        currency: string
      } | null
    }
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      current_password: string
      password: string
      password_confirmation: string
    }
    /** ClienteCollection */
    ClienteCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** ClienteResource */
    ClienteResource: {
      id: string
      /** @constant */
      type: 'cliente'
      attributes: {
        nome: string
        nif: string
        email: string
        telefone: string
        morada: string
      }
      created_at: string | null
      updated_at: string | null
    }
    /** ContaCollection */
    ContaCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** ContaResource */
    ContaResource: {
      id: string
      /** @constant */
      type: 'conta'
      attributes: {
        codigo: string
        designacao: string
        tipo: string
        conta_pai_id: string
        permite_lancamentos: string
      }
      created_at: string | null
      updated_at: string | null
    }
    /** CreateArtigoRequest */
    CreateArtigoRequest: {
      codigo: string
      nome: string
      preco_unitario: number
      moeda?: string | null
      taxa_iva?: number | null
      unidade?: string | null
    }
    /** CreateClienteRequest */
    CreateClienteRequest: {
      nome: string
      nif?: string | null
      /** Format: email */
      email?: string | null
      telefone?: string | null
      morada?: string | null
    }
    /** CreateContaRequest */
    CreateContaRequest: {
      codigo: string
      designacao: string
      /** @enum {string} */
      tipo: 'activo' | 'passivo' | 'capital_proprio' | 'proveito' | 'custo'
      /** Format: uuid */
      conta_pai_id?: string | null
      permite_lancamentos: boolean
    }
    /** CreatePeriodoContabilRequest */
    CreatePeriodoContabilRequest: {
      ano_fiscal: number
      mes: number
    }
    /** CreatePeriodoFiscalRequest */
    CreatePeriodoFiscalRequest: {
      ano_fiscal: number
      /** @description Omitido ou 0 = fecho do ano inteiro; 1-12 = fecho apenas do mês. */
      mes?: number | null
    }
    /** CreateSerieRequest */
    CreateSerieRequest: {
      tipo_documento: components['schemas']['TipoDocumentoEnum']
      codigo: string
      ano_fiscal: number
    }
    /** CreateTaxaCambioRequest */
    CreateTaxaCambioRequest: {
      /** @description AOA nunca tem taxa própria (ver TaxaCambioService::obterTaxa). */
      moeda: string
      taxa: number
      /** Format: date-time */
      data: string
    }
    /** CreateUserRequest */
    CreateUserRequest: {
      name: string
      /** Format: email */
      email: string
      role: string
    }
    /** CriarLancamentoRequest */
    CriarLancamentoRequest: {
      /** Format: uuid */
      periodo_id: string
      /** Format: date-time */
      data: string
      descricao: string
      linhas: {
        /** Format: uuid */
        conta_id: string
        debito?: number | null
        credito?: number | null
      }[]
    }
    /** DemonstracaoResultadosResource */
    DemonstracaoResultadosResource: {
      proveitos: components['schemas']['LinhaDemonstrativoResource'][]
      custos: components['schemas']['LinhaDemonstrativoResource'][]
      total_proveitos: {
        amount: string
        currency: string
      } | null
      total_custos: {
        amount: string
        currency: string
      } | null
      resultado_liquido: {
        amount: string
        currency: string
      } | null
    }
    /** EmitirFaturaRequest */
    EmitirFaturaRequest: {
      /** Format: uuid */
      serie_id: string
      /**
       * @description NC/ND só se emitem via POST /faturas/{id}/anular, nunca directamente.
       * @enum {string}
       */
      tipo_documento: 'FT' | 'FR' | 'VD' | 'RC'
      /** Format: uuid */
      cliente_id?: string | null
      moeda?: string | null
      taxa_cambio?: number | null
      linhas: {
        /** Format: uuid */
        artigo_id?: string | null
        descricao: string
        quantidade: number
        preco_unitario?: number | null
      }[]
    }
    /** ExportarSaftRequest */
    ExportarSaftRequest: {
      ano_fiscal: number
      mes?: number | null
    }
    /** FaturaCollection */
    FaturaCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** FaturaResource */
    FaturaResource: {
      id: string
      /** @constant */
      type: 'fatura'
      attributes: {
        numero: string
        tipo_documento: string
        estado: string
        serie_id: string
        cliente_id: string
        subtotal: {
          amount: string
          currency: string
        } | null
        total_iva: {
          amount: string
          currency: string
        } | null
        total: {
          amount: string
          currency: string
        } | null
        taxa_cambio: string
        hash: string
        hash_anterior: string
        fatura_original_id: string
        motivo_anulacao: string
        data_emissao: string | null
        linhas:
          | {
              id: string
              artigo_id: string
              descricao: string
              quantidade: string
              preco_unitario: {
                amount: string
                currency: string
              } | null
              taxa_iva: string
              subtotal: {
                amount: string
                currency: string
              } | null
              valor_iva: {
                amount: string
                currency: string
              } | null
              total: {
                amount: string
                currency: string
              } | null
            }[]
          | null
      }
      created_at: string | null
      updated_at: string | null
    }
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /** Format: email */
      email: string
    }
    /** LancamentoCollection */
    LancamentoCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** LancamentoResource */
    LancamentoResource: {
      id: string
      /** @constant */
      type: 'lancamento'
      attributes: {
        numero: string
        periodo_id: string
        data: string | null
        descricao: string
        estado: string
        tipo_origem: string
        origem_tipo: string
        origem_id: string
        lancamento_estorno_id: string
        linhas:
          | {
              id: string
              conta_id: string
              debito: {
                amount: string
                currency: string
              } | null
              credito: {
                amount: string
                currency: string
              } | null
            }[]
          | null
      }
      created_at: string | null
      updated_at: string | null
    }
    /** LinhaDemonstrativoResource */
    LinhaDemonstrativoResource: {
      conta_id: string
      conta_codigo: string
      conta_designacao: string
      valor: {
        amount: string
        currency: string
      } | null
    }
    /** LoginRequest */
    LoginRequest: {
      /** Format: email */
      email: string
      password: string
    }
    /** PagamentoCollection */
    PagamentoCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** PagamentoResource */
    PagamentoResource: {
      id: string
      /** @constant */
      type: 'pagamento'
      attributes: {
        fatura_id: string
        valor: {
          amount: string
          currency: string
        } | null
        metodo: string
        referencia: string
        data_pagamento: string | null
      }
      created_at: string | null
      updated_at: string | null
    }
    /** PeriodoContabilCollection */
    PeriodoContabilCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** PeriodoContabilResource */
    PeriodoContabilResource: {
      id: string
      /** @constant */
      type: 'periodo_contabil'
      attributes: {
        ano_fiscal: string
        mes: string
        fechado: string
        fechado_em: string | null
      }
      created_at: string | null
      updated_at: string | null
    }
    /** PeriodoFiscalCollection */
    PeriodoFiscalCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** PeriodoFiscalResource */
    PeriodoFiscalResource: {
      id: string
      /** @constant */
      type: 'periodo_fiscal'
      attributes: {
        ano_fiscal: string
        mes: string
        fechado: string
        fechado_em: string | null
      }
      created_at: string | null
      updated_at: string | null
    }
    /** RegistarPagamentoRequest */
    RegistarPagamentoRequest: {
      valor: number
      /** @enum {string} */
      metodo: 'transferencia' | 'numerario' | 'outro'
      referencia?: string | null
      /** Format: date-time */
      data_pagamento?: string | null
    }
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      token: string
      password: string
      password_confirmation: string
    }
    /** SaldoContaResource */
    SaldoContaResource: {
      conta_id: string
      conta_codigo: string
      conta_designacao: string
      saldo_anterior: {
        amount: string
        currency: string
      } | null
      debito: {
        amount: string
        currency: string
      } | null
      credito: {
        amount: string
        currency: string
      } | null
      saldo_atual: {
        amount: string
        currency: string
      } | null
    }
    /** SerieDocumentoCollection */
    SerieDocumentoCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** SerieDocumentoResource */
    SerieDocumentoResource: {
      id: string
      /** @constant */
      type: 'serie_documento'
      attributes: {
        tipo_documento: string
        codigo: string
        ano_fiscal: string
        ultimo_numero: string
        activa: string
      }
      created_at: string | null
      updated_at: string | null
    }
    /** TaxaCambioCollection */
    TaxaCambioCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** TaxaCambioResource */
    TaxaCambioResource: {
      id: string
      /** @constant */
      type: 'taxa_cambio'
      attributes: {
        moeda: string
        taxa: string
        data: string
      }
      created_at: string | null
      updated_at: string | null
    }
    /**
     * TipoDocumentoEnum
     * @description FT/FR/VD/RC são documentos "originais"; NC/ND só existem a referenciar um documento original (nunca se apaga uma factura — ver ADR-008).
     * @enum {string}
     */
    TipoDocumentoEnum: 'FT' | 'FR' | 'NC' | 'ND' | 'VD' | 'RC'
    /** UpdateClienteRequest */
    UpdateClienteRequest: {
      nome?: string
      nif?: string | null
      /** Format: email */
      email?: string | null
      telefone?: string | null
      morada?: string | null
    }
    /** UpdateContaRequest */
    UpdateContaRequest: {
      designacao: string
      /** Format: uuid */
      conta_pai_id?: string | null
      permite_lancamentos: boolean
    }
    /** UpdateUserRequest */
    UpdateUserRequest: {
      name?: string
      /** Format: email */
      email?: string
      role?: string
    }
    /** UserCollection */
    UserCollection: {
      data: string
      meta: {
        current_page: string
        per_page: string
        total: string
        last_page: string
      }
      links: {
        first: string
        last: string
        prev: string
        next: string
      }
    }
    /** UserResource */
    UserResource: {
      id: string
      /** @constant */
      type: 'user'
      attributes: {
        name: string
        email: string
        must_change_password: string
        roles: {
          relations: ['roles']
        }[]
        permissions: unknown[]
      }
      created_at: string | null
      updated_at: string | null
    }
  }
  responses: {
    /** @description Validation error */
    ValidationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Errors overview. */
          message: string
          /** @description A detailed description of each field that failed validation. */
          errors: {
            [key: string]: string[]
          }
        }
      }
    }
    /** @description Unauthenticated */
    AuthenticationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string
        }
      }
    }
    /** @description Authorization error */
    AuthorizationException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string
        }
      }
    }
    /** @description Not found */
    ModelNotFoundException: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  'contabilidade.apuramento-iva.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApurarIvaRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ApuramentoIvaResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.apuramento-iva.show': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The apuramento iva ID */
        apuramentoIva: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `ApuramentoIvaResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ApuramentoIvaResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.artigos.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `ArtigoCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ArtigoCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'faturacao.artigos.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateArtigoRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ArtigoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.artigos.show': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The artigo ID */
        artigo: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `ArtigoResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ArtigoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'auth.login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: {
              token: string
              must_change_password: string
              user: components['schemas']['UserResource']
            }
          }
        }
      }
      422: components['responses']['ValidationException']
    }
  }
  'auth.forgot-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            message: 'Se o email existir, vais receber instruções para repor a senha.'
          }
        }
      }
      422: components['responses']['ValidationException']
    }
  }
  'auth.reset-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest']
      }
    }
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      422: components['responses']['ValidationException']
    }
  }
  'auth.logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'auth.me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
    }
  }
  'auth.change-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest']
      }
    }
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['AuthenticationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.clientes.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `ClienteCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ClienteCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'faturacao.clientes.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateClienteRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ClienteResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.clientes.show': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The cliente ID */
        cliente: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `ClienteResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ClienteResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.clientes.update': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The cliente ID */
        cliente: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateClienteRequest']
      }
    }
    responses: {
      /** @description `ClienteResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ClienteResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.contas.index': {
    parameters: {
      query?: {
        search?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `ContaCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContaCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'contabilidade.contas.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateContaRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ContaResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.contas.update': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The conta ID */
        conta: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateContaRequest']
      }
    }
    responses: {
      /** @description `ContaResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['ContaResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.faturas.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `FaturaCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FaturaCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'faturacao.faturas.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmitirFaturaRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['FaturaResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.faturas.show': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fatura ID */
        fatura: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `FaturaResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['FaturaResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.faturas.anular': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fatura ID */
        fatura: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AnularFaturaRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['FaturaResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.faturas.pdf': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fatura ID */
        fatura: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: {
              url: string
            }
          }
        }
      }
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            message: 'O PDF está a ser gerado; tenta novamente dentro de momentos.'
            /** @constant */
            code: 'PDF_EM_GERACAO'
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.faturas.qrcode': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fatura ID */
        fatura: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/png': string
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'contabilidade.lancamentos.index': {
    parameters: {
      query?: {
        periodo_id?: string
        estado?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `LancamentoCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LancamentoCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'contabilidade.lancamentos.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CriarLancamentoRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['LancamentoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.lancamentos.show': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The lancamento ID */
        lancamento: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `LancamentoResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['LancamentoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'contabilidade.lancamentos.anular': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The lancamento ID */
        lancamento: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: {
              original: components['schemas']['LancamentoResource']
              estorno: components['schemas']['LancamentoResource']
            }
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.pagamentos.index': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fatura ID */
        fatura: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `PagamentoCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PagamentoCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.pagamentos.store': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The fatura ID */
        fatura: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegistarPagamentoRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['PagamentoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.periodos.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `PeriodoContabilCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PeriodoContabilCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'contabilidade.periodos.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePeriodoContabilRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['PeriodoContabilResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.periodos.fechar': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The periodo contabil ID */
        periodoContabil: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `PeriodoContabilResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['PeriodoContabilResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.periodos-fiscais.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `PeriodoFiscalCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PeriodoFiscalCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'faturacao.periodos-fiscais.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePeriodoFiscalRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['PeriodoFiscalResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.periodos-fiscais.fechar': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The periodo fiscal ID */
        periodoFiscal: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `PeriodoFiscalResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['PeriodoFiscalResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'contabilidade.balancete': {
    parameters: {
      query: {
        periodo_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Array of `SaldoContaResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['SaldoContaResource'][]
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.balanco': {
    parameters: {
      query: {
        periodo_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `BalancoResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['BalancoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'contabilidade.demonstracao-resultados': {
    parameters: {
      query: {
        periodo_id: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `DemonstracaoResultadosResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['DemonstracaoResultadosResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.saft.exportar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExportarSaftRequest']
      }
    }
    responses: {
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @constant */
            message: 'Exportação SAF-T iniciada; o ficheiro ficará disponível no armazenamento em breve.'
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.series.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `SerieDocumentoCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SerieDocumentoCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'faturacao.series.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSerieRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['SerieDocumentoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'faturacao.series.show': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The serie ID */
        serie: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `SerieDocumentoResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['SerieDocumentoResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'faturacao.taxas-cambio.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `TaxaCambioCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaxaCambioCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'faturacao.taxas-cambio.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTaxaCambioRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['TaxaCambioResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'admin.users.index': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `UserCollection` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserCollection']
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
    }
  }
  'admin.users.store': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: {
              user: components['schemas']['UserResource']
              temporary_password: string
            }
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      422: components['responses']['ValidationException']
    }
  }
  'admin.users.show': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The user ID */
        user: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
  'admin.users.update': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The user ID */
        user: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest']
      }
    }
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: components['schemas']['UserResource']
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'admin.users.destroy': {
    parameters: {
      query: {
        reason: string
      }
      header?: never
      path: {
        /** @description The user ID */
        user: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
      422: components['responses']['ValidationException']
    }
  }
  'admin.users.reset-password': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The user ID */
        user: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            data: {
              temporary_password: string
            }
          }
        }
      }
      401: components['responses']['AuthenticationException']
      403: components['responses']['AuthorizationException']
      404: components['responses']['ModelNotFoundException']
    }
  }
}
